# Configuración del proyecto en modo "libro"

project:
  type: book
  execute-dir: project
  output-dir: _book
  
# Configuración del libro

book:
  title: "Informe Encuesta Metodología y Técnicas Cuantitativas"
  author: "Metodología Cuantitativa"
  date: now
  page-navigation: true
  chapters:
    - index.qmd
    - design.qmd
    - cleaning.qmd
    - geo.qmd
    - text.qmd
    - redes.qmd
    - references.qmd

bibliography: [bibliography.bib]
#csl: chicago-author-date.csl 
# Esta es la opcion csl (citattion style) que viene por defecto
# Por ahora hay problemas con el path de un csl alternativo

format:
  html:
    theme: cosmo
    code-fold: true
    embed-resources: true
    self-contained-math: true # Esto es necesario para algunos gráficos interactivos
  pdf:
    documentclass: scrreprt
    
execute: 
  warning: false
  echo: false
  freeze: false 
  
editor: visual
lang: es

# title: "Diego Armando Datos"
# author: "Metodistas del Sur"
# date: "`r Sys.Date()`"
# site: bookdown::bookdown_site
# documentclass: book
# bibliography: [book.bib, packages.bib]
# url: your book url like https://bookdown.org/yihui/bookdown
# cover-image: path to the social sharing image like images/cover.jpg
# description: |
#   Informe que muestra opciones de análisis de datos básicas y complejas sobre un formulario de google forms analizado con el programa R. El mismo tiene fines pedagógicos más que académicos.
# biblio-style: apalike
# csl: chicago-fullnote-bibliography.csl
