project:
  type: book

book:
  title: "Informe Encuesta Metodología y Técnicas Cuantitativas"
  author: "Metodología Cuantitativa"
 # cover-image: "Inputs/Images/formulas_mujer.png"
  search: true
  downloads: epub
  date: now
  chapters:
    - part: "Parte 1. Diseño y preparación de los datos"
      chapters:
        - index.qmd
        - design.qmd
        - cleaning.qmd
    - part: intro_fuentes_secundarias.qmd
      chapters: 
        - hacinamiento.qmd
    - part: "Parte 3. Análisis más complejos"
      chapters:
        - geo.qmd
        - text.qmd
        - redes.qmd
        - references.qmd

bibliography: [bibliography.bib]
#csl: chicago-author-date.csl 
# Esta es la opcion csl (citattion style) que viene por defecto
# Por ahora hay problemas con el path de un csl alternativo

format:
  html:
    theme: cosmo
    code-fold: true
    embed-resources: true
    number-sections: true
  pdf:
    documentclass: scrreprt
  epub:
    title: "Informe Encuesta Metodología y Técnicas Cuantitativas"
    
execute:
  freeze: true
  warning: false
  echo: false

editor: visual
lang: es

# title: "Diego Armando Datos"
# author: "Metodistas del Sur"
# date: "`r Sys.Date()`"
# site: bookdown::bookdown_site
# documentclass: book
# bibliography: [book.bib, packages.bib]
# url: your book url like https://bookdown.org/yihui/bookdown
# cover-image: path to the social sharing image like images/cover.jpg
# description: |
#   Informe que muestra opciones de análisis de datos básicas y complejas sobre un formulario de google forms analizado con el programa R. El mismo tiene fines pedagógicos más que académicos.
# biblio-style: apalike
# csl: chicago-fullnote-bibliography.csl
