<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>hacinamiento</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="hacinamiento_files/libs/clipboard/clipboard.min.js"></script>
<script src="hacinamiento_files/libs/quarto-html/quarto.js"></script>
<script src="hacinamiento_files/libs/quarto-html/popper.min.js"></script>
<script src="hacinamiento_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hacinamiento_files/libs/quarto-html/anchor.min.js"></script>
<link href="hacinamiento_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hacinamiento_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hacinamiento_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hacinamiento_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hacinamiento_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<section id="complementación-con-fuentes-secundarias" class="level1">
<h1>Complementación con fuentes secundarias</h1>
<section id="hacinamiento" class="level2">
<h2 class="anchored" data-anchor-id="hacinamiento">Hacinamiento</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">i_am</span>(<span class="st">"hacinamiento.qmd"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at C:/Users/dquar/OneDrive/Documentos/R-Studio Projects/cuanti_encuesta_quarto</code></pre>
</div>
</div>
<p>Uno de los objetivos de la materia es, como se detalla en el programa, aportar herramientas que permitan la producción de un dato primario de calidad. Sin embargo, también es cierto que una de las maneras de agregarle valor a cualquier dato primario es su pertinente combinación con algún otro dato secundario ya existente. Por otro lado, existen situaciones en donde el uso exclusivo de fuentes secundarios es la mejor opción. Ejemplos típicos pueden considerarse:</p>
<p>a) Por las razones que sean, se estima inviable la producción de un dato primario y/o</p>
<p>b) El dato necesario ya existe en forma de datos secundario,</p>
<p>A continuación, a modo de ejemplo de como complementar un dato primario con otro secundario, se hará un análisis que utilice tanto datos de la encuesta (como fuente primaria) como algunos datos del censo de 2010 (como fuente secundaria).</p>
</section>
<section id="insumos-de-la-encuesta" class="level2">
<h2 class="anchored" data-anchor-id="insumos-de-la-encuesta">Insumos de la encuesta</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Levanto el dataset de la encuesta</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>df_encuesta <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"Outputs"</span>, <span class="st">"df_encuesta.rds"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>En la encuesta existe un módulo de “vivienda” en donde se encuentran una serie de preguntas que refieren a la vivienda del encuestado. Algunas tienen más que ver con la ubicación de la vivienda (calle, altura, etc.) y sirven para georreferenciar a los encuestados. Otras tienen que ver con características constructivas de la vivienda (piso, baño, cantidad de habitaciones, etc), otras con la relación legal del hogar con la vivienda (dueño, inquilino, etc.). La encuesta también contiene un pequeño módulo sobre el “hogar” en donde se incluyen preguntas como la cantidad y tipo de personas que conforman el hogar. En este sentido, el hogar se entiende como algo diferenciable de la vivienda y en una misma vivienda puede haber más de un hogar. En efecto, la definición que utiliza el INDEC para hogar es la de persona o grupo de personas, parientes o no, que viven bajo el mismo techo y comparten los gastos de alimentación.</p>
<p>Con este tipo de preguntas se puede construir un indicador relativamente difundido en las ciencias sociales como es el indicador de <strong>hacimamiento</strong>. Este se calcula para hogares y, de manera transitiva, luego se puede calcular para las personas. Existen varias definiciones operacionales (o criterios de medición) del concepto de hacinamiento aunque como idea general se puede afirmar que en cualquier definición de hacinamiento hay una relación explícita entre la cantidad y tipos de ambientes de la vivienda y la cantidad y tipo de miembros del hogar. Aunque muchas veces la relación anterior quede alga opacada por la discusión de cual es el punto de corte óptimo, lo que existe por detrás de la definición es la creencia (más o menos justificada según el caso) que el hacinamiento posee riegos asociados con efectos consideras como negativos y que estos se deben, en parte, al inadecuado espacio dentro del vivienda para dormir y, más en general, al inadecuado espacio para realizar otras actividades dentro de la vivienda como estudiar, socializar, etc.. En este sentido, la pandemia de COVID-19 puso de relieve no sólo la cuestión de la (falta de) disponibilidad de dispositivos tecnológicos sino también la cuestion de la (falta de) disponibilidad de espacio para realizar algunas tareas en la casa como el trabajo y/o el estudio.</p>
<p>Es interesante volver a destacar que no sólo importa el “punto de corte” a partir del cual se considera hacinamiento (¿2 personas por ambiente?, ¿3 por ambiente?) sino también:</p>
<p>a) el tipo de ambiente (¿se debe contar sólo aquellos que se utilizan para dormir?) y</p>
<p>b) el tipo de relación entre los miembros (no es lo mismo que en una habitación duerman una “pareja” que 2 hermanos entre 12 y 17 años de diferente sexo …aunque en ambos casos la cantidad de personas sean 2).</p>
<p>En Argentina históricamente se le ha dado importancia al tipo de ambiente pero en Europa desde hace varias décadas también se calcula en base al tipo de relaciones entre los miembros del hogar.</p>
<p>Idealmente, la discusión sobre el punto de corte, más que explicitarse (como lo suguiere la típica idea de la definición operacional), debería justificarse en base a (otras) investigaciones empíricas que validen que ese criterio utilizado es mejor que otros criterios alternativos/competidores en cuanto a predecir algún valor considerado como <em>gold standard</em> en el mediano/largo plazo. Esto es un ejemplo de lo que se suele denominar <strong>validación de criterio</strong> en las ciencias sociales.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Historia del concepto de hacinamiento
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A diferencia de otros conceptos más neutros en su terminología , el concepto de <strong>hacinamiento</strong> (<em>overcrowding</em>) posee una connotación negativa en el mismo sentido que el concepto de <strong>pobreza</strong>. Consecuentemente, se suelen utilizar para construir proposiciones en donde se evidencien sus efectos negativos en diferentes dominios de la realidad social. En otras palabras, a mayor hacinamiento se esperan mayores efectos negativos en otras dimensiones.</p>
<p>Por otro lado, el concepto de hacinamiento tiene una relación íntima con el concepto de <strong>densidad</strong> <strong>poblacional</strong><em>.</em> Sin embargo, este último no contiene, de modo necesario, una connotación negativa como el primero. En ambos se encuentra por detras la idea de relacionar aspectos poblacionales (p.e. cantidad de personas en un hogar en el primero y cantidad de personas en determinada administrativa en el segundo) con algún aspecto que implique alguna restricción espacial (p.e. cantidad de habitaciones en el primero, cantidad de kilómetros cuadrados en el segundo).</p>
<div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Hacinamiento</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Densidad poblacional</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p><img src="Inputs/Images/hacinamiento_groucho.jpg" class="img-fluid"></p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p><img src="Inputs/Images/densidad_edificios.jpg" class="img-fluid"></p>
</div>
</div>
</div>
<p>En efecto, es después del crecimiento de las ciudades fabriles de la revolución industrial y la difusión de la hipótesis Malthusiana sobre el crecimiento de la población, que las ideas de hacinamiento y densidad poblacional se comienzan a relacionar más explícitamente. Pero cabe destacar que, al menos desde un punto de vista metodológico, guardan una importante diferencia. La densidad poblacional refiere sobre unidades administrativas y el hacinamiento predica sobre los hogares. Esto permite que la densidad poblacional de una unidad administrativa se pueda calcular con datos agregados de esa unidad administrativa mientras que para el cálculo de la tasa de hacinamiento de esa misma unidad administrativa se necesita relacionar la cantidad de personas con la cantidad de ambientes de <strong>cada una</strong> de sus viviendas.</p>
<p>Hasta mediados del siglo XX, cuando todavía no se preguntaba por la cantidad de personas y ambientes en la vivienda en muchos censos, era usual utilizar el valor de la densidad poblacional como un indicador del hacinamiento. Si bien puede ser una decisión razonable en contextos de escases de información, esa estrategia contiene el problema metodológico de la <a href="https://es.wikipedia.org/wiki/Falacia_ecol%C3%B3gica" title="Ir a falacia ecológica">falacia ecológica</a>.</p>
<p>La situación anterior cambió bastante cuando, a mediados del siglo XX una nueva ola de investigaciones, con origen en la biología, encontraron a través de diseños experimentales una relación positiva entre convivir con otros animales en un hábitat pequeño y aumento de la agresión y la aparición de enfermedades <span class="citation" data-cites="calhoun1962">[@calhoun1962]</span>. Este tipo de investigaciones generaron un renovado interés en el concepto de hacinamiento en las ciencias sociales por lo que se incorporaron estas preguntas en muchos censos de población e, interesante desde un punto de vista metodológico, generó una mayor cantidad de investigaciones en base a encuestas, algunas de las cuales se aplicaron con diseños longitudinales <span class="citation" data-cites="solari2012">[@solari2012]</span>.</p>
<p>Para cerrar se destaca que, al menos en muchas sociedades urbanas modernas, los problemas que se relacionan con el hacinamiento también están asociados con la pobreza por lo que es (más) difícil determinar algunas relaciones de causalidad. En otros casos, como el ejemplo de la foto de los edificios, existe alta densidad poblacional pero bajo hacinamiento en parte porque también hay baja pobreza. En otros casos, por ejemplo en regiones muy poco pobladas (piénsense en zonas muy frías como la Antártida o el Ártico) hay muy poca densidad poblacional y alto hacinamiento, pero ese tipo de hacinamiento no parece generar mayores problemas ni en la salud ni en la socialización.</p>
</div>
</div>
</div>
</section>
<section id="explorando-el-dato-primario" class="level2">
<h2 class="anchored" data-anchor-id="explorando-el-dato-primario">Explorando el dato primario</h2>
<p>Un punto metodológico interesante del concepto de hacinamiento es que puede considerar como un concepto relacional explícito. Esto, traducido a un contexto metodológico, implica que su medición empírica implica la relación de 2 variables para su cálculo por lo que, como primer paso, se deben medir 2 variables por separado que luego se relacionan mediante un cálculo. Esta característica pueder servir para mostrar el siguiente problema: ¿Se puede calcular un índice de hacinamiento relacionando las cantidades <em>agregadas</em> de habitaciones y personas de un determinado territorio?. Aquí la clave está en el término <em>agregadas</em> lo que invita a pensar en cual es el referente del concepto. ¿Son los hogares? ¿Son cada uno de los individuos que componen esos hogares? ¿En qué sentido se puede afirmar que un barrio se encuentra hacinado o, por lo menos, más o menos hacinado que otro barrio?. De modo más específico Esto también sirve para poner en práctica conceptos de la unidad 3 como la distinción entre análisis univariados y análisis bivariados.</p>
<p>A continuación se realizará un análisis univariado que indique diferentes medidas de tendencia central en función del nivel de medición de las variables. Pensar/recordar el nivel de medición de las variables es importante para pensar que medida de tendencia central es apropiada. En el caso de los conceptos de la cantidad de ambientes, cantidad de habitaciones para dormir y la cantidad de miembros del hogar la idea de <a href="https://es.wikipedia.org/wiki/N%C3%BAmero_natural">n</a><a href="https://es.wikipedia.org/wiki/N%C3%BAmero_natural" title="Ir a número natural">úmero natural</a> parece servir para representar correctamente sus propiedades. Esto implica, por ejemplo, que no tiene sentido afirmar que exista una cantidad de ambientes negativa (-3 ambientes), que la cantidad de ambientes y personas pega saltos discretos (no hay algo como 1,5 personas). Las características anteriores son esenciales en la idea de frecuencia y se puede entender como el producto de realizar la operación de contar. En esos casos se dice que la variable posee un nivel de medición de razón. ¿Porqué de razón? Justamente porque se puede aplicar, de manera legítima, la operación aritmética de dividir (<em>ratio</em>). Esta característica es la que explotan los conceptos de hacinamiento y el de densidad de población.</p>
<p>Volviendo a la cuestión del análisis univariado, a continuación se presentan las medias aritméticas para el caso de las variables de razón y el porcentaje para la variable que detecta la presencia (“SI/NO”) de un ambiente exclusivo para el estudio.</p>
<div class="cell">
<div class="cell-output-display">

<div id="uvprndfrat" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

:where(#uvprndfrat) .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

:where(#uvprndfrat) .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#uvprndfrat) .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

:where(#uvprndfrat) .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

:where(#uvprndfrat) .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

:where(#uvprndfrat) .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#uvprndfrat) .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#uvprndfrat) .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

:where(#uvprndfrat) .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

:where(#uvprndfrat) .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

:where(#uvprndfrat) .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

:where(#uvprndfrat) .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

:where(#uvprndfrat) .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

:where(#uvprndfrat) .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

:where(#uvprndfrat) .gt_from_md > :first-child {
  margin-top: 0;
}

:where(#uvprndfrat) .gt_from_md > :last-child {
  margin-bottom: 0;
}

:where(#uvprndfrat) .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

:where(#uvprndfrat) .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#uvprndfrat) .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

:where(#uvprndfrat) .gt_row_group_first td {
  border-top-width: 2px;
}

:where(#uvprndfrat) .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#uvprndfrat) .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

:where(#uvprndfrat) .gt_first_summary_row.thick {
  border-top-width: 2px;
}

:where(#uvprndfrat) .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#uvprndfrat) .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#uvprndfrat) .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

:where(#uvprndfrat) .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

:where(#uvprndfrat) .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#uvprndfrat) .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#uvprndfrat) .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#uvprndfrat) .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#uvprndfrat) .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#uvprndfrat) .gt_left {
  text-align: left;
}

:where(#uvprndfrat) .gt_center {
  text-align: center;
}

:where(#uvprndfrat) .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

:where(#uvprndfrat) .gt_font_normal {
  font-weight: normal;
}

:where(#uvprndfrat) .gt_font_bold {
  font-weight: bold;
}

:where(#uvprndfrat) .gt_font_italic {
  font-style: italic;
}

:where(#uvprndfrat) .gt_super {
  font-size: 65%;
}

:where(#uvprndfrat) .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

:where(#uvprndfrat) .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

:where(#uvprndfrat) .gt_indent_1 {
  text-indent: 5px;
}

:where(#uvprndfrat) .gt_indent_2 {
  text-indent: 10px;
}

:where(#uvprndfrat) .gt_indent_3 {
  text-indent: 15px;
}

:where(#uvprndfrat) .gt_indent_4 {
  text-indent: 20px;
}

:where(#uvprndfrat) .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="<strong>Característica</strong>"><strong>Característica</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="<strong>N = 133</strong><sup class=&quot;gt_footnote_marks&quot;>1</sup>"><strong>N = 133</strong><sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Cantidad de ambientes</td>
<td headers="stat_0" class="gt_row gt_center">3.55</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Cantidad de ambientes para dormir</td>
<td headers="stat_0" class="gt_row gt_center">2.23</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Presencia de un ambiente exclusivo para el estudio</td>
<td headers="stat_0" class="gt_row gt_center"></td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;NO</td>
<td headers="stat_0" class="gt_row gt_center">59 (44%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">&nbsp;&nbsp;&nbsp;&nbsp;SI</td>
<td headers="stat_0" class="gt_row gt_center">74 (56%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Cantidad de miembros del hogar</td>
<td headers="stat_0" class="gt_row gt_center">3.97</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="2"><sup class="gt_footnote_marks">1</sup> Media; n (%)</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
<p>Con los resultados de la tabla anterior a la mano uno se ve tentado de relacionar, más precisamente de dividir, la media de la cantidad de ambientes para dormir (<code>2.23</code>) sobre la media de la cantidad de miembros del hogar (<code>3.97</code>). Esta cuentita da que hay <code>1.78</code> personas por cada ambiente para dormir. Si es por la cuestión de los niveles de medición la operación anterior es legítima. El problema es que el concepto de hacinamiento está pensado para ser calculado para cada hogar por separado y luego, por una cuestión transitiva, imputarlo a cada miembro de ese hogar si se quiere calcular cuantas personas viven hacinadas.</p>
<p>No se trata simplemente de dividir con , respectively</p>
</section>
<section id="combinando-con-datos-censales" class="level2">
<h2 class="anchored" data-anchor-id="combinando-con-datos-censales">Combinando con datos censales</h2>
<p>Una de las fuentes secundarias por excelencia, no sólo en Argentina sino en la mayoría de los países, son los Censos nacionales de población. En este caso, utlizaremos los datos del censo del 2010.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># La idea es agarrar el csv de las personas y convertirlo a parquet file</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Esto lo hago una sola vez y dejo el código pero en próximas corridas sólo se utiliza como insumo el producto del código anterior</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arrow)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>censo_persona_csv <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"Inputs"</span>, <span class="st">"PERSONA.csv"</span>))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>censo_persona_arrow <span class="ot">&lt;-</span> <span class="fu">read_csv_arrow</span>(<span class="fu">here</span>(<span class="st">"Inputs"</span>, <span class="st">"PERSONA.csv"</span>))</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>censo_persona_sav <span class="ot">&lt;-</span> <span class="fu">read_spss</span>(<span class="fu">here</span>(<span class="st">"Inputs"</span>, <span class="st">"PERSONA.sav"</span>))</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a> <span class="fu">read_csv_arrow</span>()</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>df_encuesta <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"Outputs"</span>, <span class="st">"df_encuesta.rds"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>